### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Fouppy** [MeetMangrove/mangrove-website#1]

**Comment by maxbrodi** [comment]
ENGLISH VERSION:
- text must be adapted to device (become bigger on mobile)
- pictures (fishes on homepage, pics in other pages) must be either put before or after text, or hidden.
- the hero (gradient header) would be better if smaller on mobile
- for the menu, I used a drop-down on mobile on the first version of Mangrove's website

FRENCH VERSION:
- le texte doit s’adapter au device (devenir plus gros sur mobile, prendre toute la div par exemple pour le texte explicatif sur fond bleu foncé)
- les images (les poissons, les photos carrées…) soit vous les places après le texte, soit vous les virez si vous trouvez pas comment les agencer
- la zone dégradée peut être réduite en hauteur sur mobile
- j’avais fait un drop-down pour le menu sur mobile sur la v1 du site

**Comment by Jauny** [comment]
just pushed a pull request to help with some general responsiveness.

Still to do:
- Header. Would be nice to have a design idea of what we want to do on mobile, since there is so much that could be done.
- General CSS cleanup. I found some anti pattern that make the css on a very case-by-case basis instead of being reusable. Splitting CSS per page is usually a bad idea, because it becomes very messy as soon as we want to re-use some design from a different page. We should rename classes to represent what they do/look like. I like the BEM conventions (https://en.bem.info/methodology/naming-convention/)
- Some html cleanup too. Right now page padding are set by each elements which can quickly become a mess too (this already happened on the 'team' page since it doesn't use `section`). The use of a higher-level div to ensure consistency in padding, spacing, etc. makes things easier usually.

Really nothing in a rush as the website is very static and I don't think we'll do much more work on it... but wanted to share my 2cents :)
