### ISSUE TITLE
Members' picture

### ISSUE THREAD

**Issue by Fouppy** [MeetMangrove/mangrove-website#4]
- [ ] Grab twitter profile pic
- [ ] Fallback on the one provided

**Comment by davb** [comment]
I'm proposing #12 as a way to implement this. Feedback welcome! :)

**Comment by aegiz** [comment]
So this issue was resolved with #12 
However, I have a suggestion: atm we are using the Google spreadsheet : https://docs.google.com/spreadsheets/d/1ksK3vR4XF60SnegkSAjV3Q8SYHh-dgGUJDA4Y9RTBRE/edit#gid=955123836 on which we already have the URL of the user (tab: WebsiteV2) so why not using this instead of a third party API ?
ping @Fouppy @AmbroiseCollon

**Comment by AmbroiseCollon** [comment]
The issue came up because all urls were not for the image. So for those, we grab the image from twitter using the handle in the spreadsheet and avatars.io. Does this answer your question ? Plus avatars.io has the advantage of having a unique format for all images which is not the case at all in our spreadsheet.

**Comment by aegiz** [comment]
Ah! That make sense! So let's close this issue and mark it as resolved ?

**Comment by AmbroiseCollon** [comment]
Yes you're right we forgot to do it.
